### ISSUE TITLE
Web Service Functionality - Register

### ISSUE THREAD

**Issue by akannika** [akannika/Team-3-TCSS-450#60]
As a team developer, we want to see that our web-service that the clients be able to register and our application can store the registered users.

- [x] Web Service Functionality - Register - clients be able to register with the web service
- [x] Web Service Functionality - Register - the web service can store registered users
- [x] Web Service Functionality - Register - the web-service has appropriate raite error scenarios
- [x] Web Service Functionality - Register - the web-server perform its own validation on credentials
