### ISSUE TITLE
Web Service Functionality - Registration-Email Verify

### ISSUE THREAD

**Issue by akannika** [akannika/Team-3-TCSS-450#61]
As a user, I want the application send me the email verification to make sure that nobody use my email to register without my permission. So that when I want to create my own account, I will be able to use my email.
As a tam developer, we don't want someone use the email that they cannot get access to create the account for our application.

- [x] Web Service Functionality - Registration-Email Verify - Create the function to send the email verification to the user who want to create an account using that email.
- [x] Web Service Functionality - Registration-Email Verify - Web services include a system to verify ownership of the registered email, when the user register for the application
- [x] Web Service Functionality - Registration-Email Verify - Ensure that registered the user and store the user information into the database.
- Optional: Web Service Functionality - Registration-Email Verify - Ensure that the email verification has the time limit to verify?
